name: Build and Analyze

on:
  push:
    branches:
      - develop
      - feature*
  pull_request:
    types: [ opened, synchronize, reopened ]

defaults:
  run:
    shell: bash

jobs:

  mvn-build:
    runs-on: ubuntu-latest
    env:
      GHRNC_GITHUB_TOKEN: ${{secrets.GHRNC_GITHUB_TOKEN}}
      GHRNC_OWNER: ${{secrets.GHRNC_OWNER}}
      GHRNC_REPO: ${{secrets.GHRNC_REPO}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java and Maven
        uses: ./.github/actions/setup-java-maven/

      - name: Build with Maven
        run: mvn -DtestClasspath=src/test/ verify
